"""Criação inicial das tabelas

Revision ID: 89f1e24961d0
Revises: 
Create Date: 2025-05-20 10:58:49.165630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f1e24961d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadastro_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_empresa', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('endereco', sa.Text(), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('foto_path', sa.String(length=255), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cnae',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cnae', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['cadastro_empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagina_web',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['cadastro_empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ramo_atuacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('ramo', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['cadastro_empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome_servico', sa.String(length=255), nullable=False),
    sa.Column('descricao_servico', sa.Text(), nullable=False),
    sa.Column('preco_normal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_comunidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('foto_path', sa.String(length=255), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['cadastro_empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['cadastro_empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('servico')
    op.drop_table('ramo_atuacao')
    op.drop_table('pagina_web')
    op.drop_table('cnae')
    op.drop_table('cadastro_empresa')
    # ### end Alembic commands ###
