"""Adiciona coluna sobre_empresa

Revision ID: eb20bc60aef4
Revises: 89f1e24961d0
Create Date: 2025-05-21 16:42:48.134034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb20bc60aef4'
down_revision = '89f1e24961d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastro_empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sobre_empresa', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastro_empresa', schema=None) as batch_op:
        batch_op.drop_column('sobre_empresa')

    # ### end Alembic commands ###
